CREATE DATABASE pureti;

CREATE TABLE usuarios (
    id SERIAL PRIMARY KEY,
    userName VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
	comentario VARCHAR(255),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	fechaFin TIMESTAMPTZ
);

CREATE TABLE roles (
    id SERIAL PRIMARY KEY,
    rol VARCHAR(255) NOT NULL UNIQUE,
	comentario VARCHAR(255),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	fechaFin TIMESTAMPTZ
);

CREATE TABLE permisos (
    id SERIAL PRIMARY KEY,
    permiso VARCHAR(255) NOT NULL UNIQUE,
	comentario VARCHAR(255),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	fechaFin TIMESTAMPTZ
);

CREATE TABLE usuario_rol (
    id SERIAL PRIMARY KEY,
    idUsuario INTEGER NOT NULL,
    idRol INTEGER NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fechaFin TIMESTAMPTZ,
    FOREIGN KEY (idUsuario) REFERENCES usuarios(id) ON DELETE CASCADE,
    FOREIGN KEY (idRol) REFERENCES roles(id) ON DELETE CASCADE,
    CONSTRAINT uk_usuario_rol UNIQUE (idUsuario, idRol) 
);

CREATE TABLE rol_permiso (
    id SERIAL PRIMARY KEY,
    idRol INTEGER NOT NULL,
    idPermiso INTEGER NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fechaFin TIMESTAMPTZ,
    FOREIGN KEY (idRol) REFERENCES roles(id) ON DELETE CASCADE,
    FOREIGN KEY (idPermiso) REFERENCES permisos(id) ON DELETE CASCADE,
    CONSTRAINT uk_rol_permiso UNIQUE (idRol, idPermiso )
);

